import Head from 'next/head';
import { GetServerSideProps, NextPage } from 'next';
import { urqlClient } from '@/libs/urql';
import {
  Table,
  TableCaption,
  TableContainer,
  Tbody,
  Td,
  Th,
  Thead,
  Tr,
} from '@chakra-ui/react';
import { GetTodosDocument, TodoModel } from '@/graphql/generated/graphql';
import Header from '@/components/header';

type Props = {
  todos: TodoModel[];
};

const Home: NextPage<Props> = (props) => {
  const { todos } = props;

  return (
    <>
      <Head>
        <title>GraphQL Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TableContainer>
          <Table variant="striped" colorScheme="teal">
            <TableCaption>Todo List</TableCaption>
            <Thead>
              <Tr>
                <Th>Title</Th>
                <Th>Detail</Th>
                <Th>Created_At</Th>
                <Th>Updated_At</Th>
              </Tr>
            </Thead>
            <Tbody>
              {todos.map((todo) => {
                return (
                  <Tr key={todo.id}>
                    <Td>{todo.title}</Td>
                    <Td>{todo.detail}</Td>
                    <Td>{todo.createdAt}</Td>
                    <Td>{todo.updatedAt}</Td>
                  </Tr>
                );
              })}
            </Tbody>
          </Table>
        </TableContainer>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  try {
    const client = await urqlClient();
    const result = await client.query(GetTodosDocument, {}).toPromise();
    if (result.data) {
      return { props: { todos: result.data.getTodos } };
    } else {
      return { props: { todos: [] } };
    }
  } catch (error) {
    console.error(error);
    return {
      notFound: true,
    };
  }
};

export default Home;
