import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { GetServerSideProps, NextPage } from 'next';
import { urqlClient } from '@/libs/urql';
import { gql } from 'urql';
import {
  Table,
  TableCaption,
  TableContainer,
  Tbody,
  Td,
  Th,
  Thead,
  Tr,
} from '@chakra-ui/react';

const inter = Inter({ subsets: ['latin'] });

type Props = {
  todos: {
    id: string;
    title: string;
    detail: string;
    createdAt: string;
    updatedAt: string;
  }[];
};

const Home: NextPage<Props> = (props) => {
  const { todos } = props;
  return (
    <>
      <Head>
        <title>GraphQL Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <TableContainer>
          <Table variant="striped" colorScheme="teal">
            <TableCaption>Todo List</TableCaption>
            <Thead>
              <Tr>
                <Th>Title</Th>
                <Th>Detail</Th>
                <Th>Created_At</Th>
                <Th>Updated_At</Th>
              </Tr>
            </Thead>
            <Tbody>
              {todos.map((todo) => {
                return (
                  <Tr key={todo.id}>
                    <Td>{todo.title}</Td>
                    <Td>{todo.detail}</Td>
                    <Td>{todo.createdAt}</Td>
                    <Td>{todo.updatedAt}</Td>
                  </Tr>
                );
              })}
            </Tbody>
          </Table>
        </TableContainer>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  try {
    const client = await urqlClient();
    const todosQuery = gql`
      query GetTodos {
        getTodos {
          id
          title
          detail
          createdAt
          updatedAt
        }
      }
    `;
    const result = await client.query(todosQuery, {}).toPromise();
    return { props: { todos: result.data.getTodos } };
  } catch (error) {
    console.error(error);
    return {
      notFound: true,
    };
  }
};

export default Home;
